### ISSUE TITLE
文档核心翻译任务认领

### ISSUE THREAD

**Issue by QC-L** [denocn/deno_docs#3]
# 任务认领说明

**任务认领前，请务必阅读 [翻译流程](#7)**

> 注意：一次尽量只认领一篇，给其他小伙伴留些机会~

从 Todo List 中选取未被人领取过的文章：

未被领取过：

* [ ] Introduction

领取过：

* [ ] Getting Started (@QC-L)

领取过，已完成：

* [x] Getting Started (@QC-L) #4 

**领取方式，在本 issues 下评论即可。**

认领任务格式：

```markdown
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Getting Started |  Installation Deno | @QC-L | 2021.02.03 - 2020.02.04
```

示例效果：

Section | Title | 译者 | 完成时间
-- | -- | -- | --
Getting Started |  Installation Deno | @QC-L | 2021.02.03 - 2020.02.04

## 任务认领列表

Todo List:

- [x] [Introduction](https://github.com/denocn/deno_docs/blob/main/introduction.md) (@justjavac) #6
- [x] [Getting Started](https://github.com/denocn/deno_docs/blob/main/getting_started.md) (@QC-L) #4
  - [x] [Installing Deno](https://github.com/denocn/deno_docs/blob/main/getting_started/installation.md) (@QC-L) #5 
  - [x] [Setting up your environment](https://github.com/denocn/deno_docs/blob/main/getting_started/setup_your_environment.md) (@ajaxjiang96) #9 
  - [x] [Running a `Hello World` script](https://github.com/denocn/deno_docs/blob/main/getting_started/first_steps.md) (@ReAlign) #23 
  - [x] [Writing our own script](https://github.com/denocn/deno_docs/blob/main/getting_started/first_steps.md) (同Running a `Hello World` script) #23 
  - [x] [Command line interface](https://github.com/denocn/deno_docs/blob/main/getting_started/command_line_interface.md) (@wuqin0791) #25 
  - [x] [Understanding permissions](https://github.com/denocn/deno_docs/blob/main/getting_started/permissions.md) (@KimYangOfCat) #24 
  - [x] [Using WebAssembly](https://github.com/denocn/deno_docs/blob/main/getting_started/webassembly.md) (@wuqin0791) #33 
  - [x] [Debugging your code](https://github.com/denocn/deno_docs/blob/main/getting_started/debugging_your_code.md) (@ReAlign) #27 
- [x] [The Runtime](https://github.com/denocn/deno_docs/blob/main/runtime.md) (@ReAlign) #28 
  - [x] [Location API](https://github.com/denocn/deno_docs/blob/main/runtime/location_api.md) (@ReAlign) #29 
  - [x] [Permission APIs](https://github.com/denocn/deno_docs/blob/main/runtime/permission_apis.md) (@ReAlign) #30 
  - [x] [Program lifecycle](https://github.com/denocn/deno_docs/blob/main/runtime/program_lifecycle.md) (@kimberlyohq) #31 
  - [x] [Stability](https://github.com/denocn/deno_docs/blob/main/runtime/stability.md)(@wuqin0791 )
  - [x] [Web Platform APIs](https://github.com/denocn/deno_docs/blob/main/runtime/web_platform_apis.md)(@wuqin0791 )
  - [x] [Workers](https://github.com/denocn/deno_docs/blob/main/runtime/workers.md)(@wuqin0791 )
- [ ] [Linking to third party code](https://github.com/denocn/deno_docs/blob/main/linking_to_external_code.md)(@wuqin0791 )
  - [ ] [Reloading modules](https://github.com/denocn/deno_docs/blob/main/linking_to_external_code/reloading_modules.md)
  - [ ] [Import maps](https://github.com/denocn/deno_docs/blob/main/linking_to_external_code/import_maps.md)
  - [ ] [Integrity checking](https://github.com/denocn/deno_docs/blob/main/linking_to_external_code/integrity_checking.md)
  - [ ] [Proxies](https://github.com/denocn/deno_docs/blob/main/linking_to_external_code/proxies.md)
  - [ ] [Private](https://github.com/denocn/deno_docs/blob/main/linking_to_external_code/private.md)
- [x] [Using TypeScript](https://github.com/denocn/deno_docs/blob/main/typescript.md) (@QC-L) #4
  - [ ] [Overview of TypeScript in Deno](https://github.com/denocn/deno_docs/blob/main/typescript/overview.md)
  - [ ] [Configuring TypeScript in Deno](https://github.com/denocn/deno_docs/blob/main/typescript/configuration.md)
  - [ ] [Types and Type Declarations](https://github.com/denocn/deno_docs/blob/main/typescript/types.md)
  - [ ] [Migrating to/from JavaScript](https://github.com/denocn/deno_docs/blob/main/typescript/migration.md)
  - [ ] [Runtime compiler APIs](https://github.com/denocn/deno_docs/blob/main/typescript/runtime.md)
  - [ ] [FAQs about TypeScript in Deno](https://github.com/denocn/deno_docs/blob/main/typescript/faqs.md)
- [ ] [Standard library](https://github.com/denocn/deno_docs/blob/main/standard_library.md)
- [x] [Examples](https://github.com/denocn/deno_docs/blob/main/examples.md) (@QC-L) #4
  - Basic
    - [ ] [Hello world](https://github.com/denocn/deno_docs/blob/main/examples/hello_world.md)
    - [ ] [Import and export modules](https://github.com/denocn/deno_docs/blob/main/examples/import_export.md)
    - [ ] [Manage dependencies](https://github.com/denocn/deno_docs/blob/main/examples/manage_dependencies.md)
    - [ ] [Fetch data](https://github.com/denocn/deno_docs/blob/main/examples/fetch_data.md)
    - [ ] [Read and write files](https://github.com/denocn/deno_docs/blob/main/examples/read_write_files.md)
  - Advanced
    - [ ] [Unix cat program](https://github.com/denocn/deno_docs/blob/main/examples/unix_cat.md)
    - [ ] [HTTP web server](https://github.com/denocn/deno_docs/blob/main/examples/http_server.md)
    - [ ] [File server](https://github.com/denocn/deno_docs/blob/main/examples/file_server.md)
    - [ ] [TCP echo server](https://github.com/denocn/deno_docs/blob/main/examples/tcp_echo.md)
    - [ ] [Creating a subprocess](https://github.com/denocn/deno_docs/blob/main/examples/subprocess.md)
    - [ ] [OS signals](https://github.com/denocn/deno_docs/blob/main/examples/os_signals.md)
    - [ ] [File system events](https://github.com/denocn/deno_docs/blob/main/examples/file_system_events.md)
    - [ ] [Module metadata](https://github.com/denocn/deno_docs/blob/main/examples/module_metadata.md)
- [ ] [Testing](https://github.com/denocn/deno_docs/blob/main/testing.md)
  - [ ] [Assertions](https://github.com/denocn/deno_docs/blob/main/testing/assertions.md)
- [x] [Tools](https://github.com/denocn/deno_docs/blob/main/tools.md) (@QC-L) #4
  - [ ] [Bundling](https://github.com/denocn/deno_docs/blob/main/tools/bundler.md)
  - [ ] [Compiling Executables](https://github.com/denocn/deno_docs/blob/main/tools/compiler.md)
  - [ ] [Script installer](https://github.com/denocn/deno_docs/blob/main/tools/script_installer.md)
  - [ ] [Dependency Inspector](https://github.com/denocn/deno_docs/blob/main/tools/dependency_inspector.md)
  - [ ] [Documentation Generator](https://github.com/denocn/deno_docs/blob/main/tools/documentation_generator.md)
  - [ ] [Code formatter](https://github.com/denocn/deno_docs/blob/main/tools/formatter.md)
  - [ ] [REPL](https://github.com/denocn/deno_docs/blob/main/tools/repl.md)
  - [ ] [Linter](https://github.com/denocn/deno_docs/blob/main/tools/linter.md)
- [x] [Embedding Deno](https://github.com/denocn/deno_docs/blob/main/embedding_deno.md) (@QC-L) #4
- [ ] [Contributing](https://github.com/denocn/deno_docs/blob/main/contributing.md)
  - [ ] [Architecture](https://github.com/denocn/deno_docs/blob/main/contributing/architecture.md)
  - [ ] [Building from source](https://github.com/denocn/deno_docs/blob/main/contributing/building_from_source.md)
  - [ ] [Development tools](https://github.com/denocn/deno_docs/blob/main/contributing/development_tools.md)
  - [ ] [Release Schedule](https://github.com/denocn/deno_docs/blob/main/contributing/release_schedule.md)
  - [x] [Deno Style Guide](https://github.com/denocn/deno_docs/blob/main/contributing/style_guide.md) (@Kyya) #10 
  - [ ] [Web Platform Test](https://github.com/denocn/deno_docs/blob/main/contributing/web_platform_tests.md)

**Comment by kyya** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Contributing |  Deno Style Guide | @Kyya | 2021.02.09 - 2020.02.10

**Comment by ajaxjiang96** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Getting Started | Setting up your environment | @AjaxJiang96 | 2021.02.09 - 2020.02.10

**Comment by ReAlign** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Getting Started | Running a `Hello World` script | @ReAlign | 2021.05.10 - 2021.05.13

**Comment by ReAlign** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Getting Started | Debugging your code | @ReAlign | 2021.05.15 - 2021.05.18

**Comment by wuqin0791** [comment]
>Section | Title | 译者 | 完成时间
-- | -- | -- | --
Getting Started | Command line interface | @wuqin0791 | 2021.05.14 - 2021.05.15

**Comment by wuqin0791** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Getting Started | Command line interface | @wuqin0791 | 2021.05.14 - 2021.05.17

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Getting Started |  Understanding permissions  | @KimYangOfCat | 2021.05.14 - 2020.05.16

**Comment by wuqin0791** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Getting Started | Using WebAssembly | @wuqin0791 | 2021.05.23 - 2021.05.25

**Comment by ReAlign** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
The Runtime | Location API | @ReAlign | 2021.05.19 - 2021.05.19

**Comment by ReAlign** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
The Runtime | Permission APIs | @ReAlign | 2021.05.19 - 2021.05.20

**Comment by ReAlign** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
The Runtime | The Runtime | @ReAlign | 2021.05.19 - 2021.05.19

**Comment by kimberlyohq** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
The Runtime |  Program lifecycle | @kimberlyohq | 2021.05-21 - 2021.05.21

**Comment by wuqin0791** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
The Runtime |  Stability | @wuqin0791  | 2021.05-29 - 2021.05.31

**Comment by wuqin0791** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
The Runtime |  Web Platform APIs | @wuqin0791  | 2021.06-04 - 2021.06.07

**Comment by wuqin0791** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
The Runtime |  Workers | @wuqin0791  | 2021.06-12 - 2021.06.12

**Comment by wuqin0791** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Linking to third party code | Linking to third party code | @wuqin0791  | 2021.06-19 - 2021.06.20

**Comment by kylezhang** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Linking to third party code |  reloading_modules | @kylezhang| 2021.12.26 - 2020.12.27

**Comment by GaoNeng-wWw** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Linking to third party code |  Import maps | @GaoNeng-wWw | 2022.2.17 - 2022.2.17
